#!/bin/sh
# Make the output files for each test

if [ ! -f ../bin/b ]
then echo "Need to build ../bin/b first!"; exit 1
fi

for i in input*
do if [ ! -f "out.$i" ]
   then
     ../bin/b $i
     cc -o out out.s
     ./out > out.$i
     rm -f out out.s
   fi
done
